const path = require('path');

module.exports = {
   apps: [
      {
         name: 'Vanusa-main',
         script: path.resolve(__dirname, './dist/index.js'),
         interpreter: 'node',
         exec_mode: 'fork',
         watch: false,
         autorestart: false,
         min_uptime: '2s',
         instances: 1,
         max_memory_restart: '400M',
         max_restarts: 2,
         log_file: path.resolve(__dirname, './logs/main_log.txt'),
         env: {
            NODE_ENV: 'production',
            windowsHide: true,
            vizion: false,
            silent: true,
         },
      },
      {
         name: 'Vanusa-monitor',
         script: path.resolve(__dirname, './dist/utils/PM2-monitor.js'),
         interpreter: 'node',
         exec_mode: 'fork',
         watch: false,
         autorestart: true,
         log_file: path.resolve(__dirname, './logs/monitor_log.txt'),
         env: {
            NODE_ENV: 'production',
            windowsHide: true,
            vizion: false,
            silent: true,
         },
         instances: 1,
         max_restarts: 3,
         vizion: false,
         windowsHide: true,
      },
      {
         name: 'V-node-red',
         script: path.resolve(__dirname, './node_modules/node-red/red.js'),
         exec_mode: 'fork',
         args: ' ./VoiceAssist.json -p 21105 --settings ./settings.cjs',
         cwd: path.resolve(__dirname, './.node-red'),
         instances: 1,
         watch: true,
         max_restarts: 3,
         vizion: false,
         windowsHide: true,
         max_memory_restart: '3G',
         log_file: path.resolve(__dirname, './logs/red_log.txt'),
         env: {
            npm_config_cache: '/tmp/.npm-cache',
            NODE_ENV: 'production',
            windowsHide: true,
            vizion: false,
            silent: true,
            RED_PORT: '21105',
         },
      },
   ],
};
