module.exports = {
   apps: [
      {
         name: 'Vanusa-main',
         script: './dist/index.js',
         interpreter: 'node',
         exec_mode: 'fork',
         watch: false,
         autorestart: false,
         min_uptime: '2s',
         instances: 1,
         max_memory_restart: '400M',
         max_restarts: 2,
         env: {
            NODE_ENV: 'production',
            windowsHide: true,
            vizion: false,
            silent: true,
         },
      },
      {
         name: 'Vanusa-monitor',
         script: './dist/utils/PM2-monitor.js',
         interpreter: 'node',
         exec_mode: 'fork',
         watch: false,
         autorestart: true,
         env: {
            NODE_ENV: 'production',
            windowsHide: true,
            vizion: false,
            silent: true,
         },
         instances: 1,
         max_restarts: 3,
         vizion: false,
         windowsHide: true,
      },
      {
         name: 'V-node-red',
         script: './node_modules/node-red/red.js',
         exec_mode: 'fork',
         args: ' ./VoiceAssist.json -p 21105 --settings ./settings.cjs',
         cwd: './.node-red',
         instances: 1,
         watch: true,
         max_restarts: 3,
         vizion: false,
         windowsHide: true,
         max_memory_restart: '3G',
         env: {
            npm_config_cache: '/tmp/.npm-cache',
            NODE_ENV: 'production',
            windowsHide: true,
            vizion: false,
            silent: true,
         },
      },
   ],
};
